//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
<<<<<<< HEAD
        public int CartDetailId { get; set; }
        public int OrderCartId { get; set; }
        public string MenuId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartDetail()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public int CartDetailID { get; set; }
        public int OrderCartID { get; set; }
        public System.Guid MenuID { get; set; }
        public System.Guid CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual OrderCart OrderCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
>>>>>>> f5516eec2c1b5177ee5e3e0373a699da3ff4b92e
    }
}
