//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishSubCategory
    {
        public System.Guid SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public System.Guid DishCategoryID { get; set; }
    
        public virtual DishCategory DishCategory { get; set; }
    }
}
