//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid InvoiveID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public decimal ITotal { get; set; }
        public int CartDetailID { get; set; }
    
        public virtual CartDetail CartDetail { get; set; }
    }
}
