//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCart
    {
<<<<<<< HEAD
        public System.Guid OrderCartId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderNumber { get; set; }
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCart()
        {
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public System.DateTime OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public int OrderCartID { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
>>>>>>> f5516eec2c1b5177ee5e3e0373a699da3ff4b92e
    }
}
