//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentId { get; set; }
        public System.Guid OrderID { get; set; }
        public string VAT { get; set; }
        public string ServiceTAX { get; set; }
        public string Total { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
